[build]
  command = "npm run production"
  publish = "dist"

[[redirects]]
  from = "/:year/:month/:date/:slug"
  to = "/:slug"
  status = 301

[[redirects]]
  from = "/feed/"
  to = "/rss.xml"
  status = 301

[[redirects]]
  from = "/rss/"
  to = "/rss.xml"
  status = 301

[[headers]]
  for = "/rss.xml"
  [headers.values]
    content-type = "application/rss+xml; charset=UTF-8"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = '''
      max-age=63072000
      includeSubDomains
      preload'''


